### ISSUE TITLE
Error after first attempt to execute query when permissions have been revoked

### ISSUE THREAD

**Issue by krlmlr** [r-lib/httr#325] opened 2016-01-26 22:33 UTC
Copy of https://github.com/rstats-db/bigrquery/issues/73, this seems to be an `httr` issue after all.

https://github.com/hadley/httr/pull/315#issuecomment-170003813
- Initial state: Connection from bigrquery works, no service token set
- Revoke access via https://myaccount.google.com/security#connectedapps
  - I can still connect from bigrquery for a minute or so
- Eventually, I'm seeing the following as a result from query_exec():
  
  ```
  Auto-refreshing stale OAuth token.
  No encoding supplied: defaulting to UTF-8.
  Error: Invalid Credentials
  In addition: Warning message:
  Unable to refresh token 
  9: stop(out$err$message, call. = FALSE) at request.r#67
  8: process_request(req) at request.r#34
  7: bq_post(url, body) at jobs.r#60
  6: insert_query_job(query, project, destination_table = destination_table, 
         default_dataset = default_dataset) at query.r#32
  5: query_exec(sql, project = project) at oauth.R#5
  4: eval(expr, envir, enclos)
  3: eval(ei, envir)
  2: withVisible(eval(ei, envir))
  1: source("~/git/R/bigrquery/oauth.R", echo = TRUE)
  ```
- The second call of query_exec() finally opens the authentication page in the browser

**Comment by MarkEdmondson1234** [comment] 2016-02-06 23:13
I am seeing some delayed OAuth2 authentication issues too since `httr 1.1.0`, have there been any changes to how authentication is cached?  

I can log in fine the first time, but then if I log out and back in I get a 401 error from Google - the access token is NULL ("access_token$credentials$access_token")  but the token object itself is created: 
```
Classes 'Token2.0', 'Token', 'R6' <Token2.0>
  Inherits from: <Token>
  Public:
    app: oauth_app
    cache: function (path = self$cache_path) 
    cache_path: .httr-oauth
    can_refresh: function () 
    clone: function (deep = FALSE) 
    credentials: list
    endpoint: oauth_endpoint
    hash: function () 
    init_credentials: function () 
    initialize: function (app, endpoint, params = list(), credentials = NULL, 
    load_from_cache: function () 
    params: list
    print: function (...) 
    private_key: NULL
    refresh: function () 
    revoke: function () 
    sign: function (method, url) 
    validate: function ()  
```

If I wait 10 mins it works again.

**Comment by hadley** [comment] 2018-12-04 16:42
I now _think_ that this is by design. Regardless, it's probably never going to be fixed in httr, but we're going to totally reconsider OAuth in httr2, and it may get fixed as part of the general re-think.

**Closed by hadley** 2018-12-04 16:42 UTC
Labels: bug, oauth :ping_pong:
