### ISSUE TITLE
OAuth Refusing Connection - R - Works with twitteR package, but not with httr?

### ISSUE THREAD

**Issue by Jibril2** [r-lib/httr#441] opened 2017-05-14 01:06 UTC
The code I am using is as follows...

```
myKey = "xxxxxxxxxxxx"
mySecret = "xxxxxxxxxxxxx"
accessToken = "xxxxxxxxxxxx-xxxxxxxxxxxx"
accessSecret = "xxxxxxxxxxxx"


myapp = oauth_app("twitter", key=myKey, secret=mySecret)
sig = sign_oauth1.0(myapp, token=accessToken, token_secret=accessSecret )
url = paste( "https://api.twitter.com/1.1/search/tweets.json?", "q=13+Reasons+Why", sep="")
GET(url, sig)

```

That always gives me a 401 error authentication failed.

Meanwhile, using library(twitteR)

`setup_twitter_oauth( consumer_key=myKey, consumer_secret=mySecret, access_token=accessToken, access_secret = accessSecret)
`
Accepts the OAuth.

**Comment by hadley** [comment] 2017-07-24 13:24
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by yutannihilation** [comment] 2017-07-24 13:35
I believe #424 will fix this issue.

@Jibril2 If you use `"q=13ReasonsWhy"` instead of `"q=13+Reasons+Why"`, the status code will be 200, right? I think this is because `oauth_encode()` fails to handle `+`.

**Comment by yutannihilation** [comment] 2017-07-24 15:43
> I believe #424 will fix this issue.

Sorry, this was my misunderstanding...

The issue seems involved with the order of parsing the URL and generating the signature, which may not be fixed easily.

``` r
# 401
GET(url, sig)

# OK
GET(parse_url(url), sig)
# OK
GET("https://api.twitter.com/1.1/search/tweets.json",
    query = list(q = "13+Reasons+Why"), sig)
```

**Comment by hadley** [comment] 2017-08-01 13:32
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-08-01 13:32 UTC
Labels: oauth, reprex
