### ISSUE TITLE
Unable to implement OAuth 1.0a (One-Legged) 

### ISSUE THREAD

**Issue by cdr6934** [r-lib/httr#447] opened 2017-06-01 04:24 UTC
I am trying to use the OAuth 1.0 (One-Legged) authentication as defined in the [Oauth Bible ](http://oauthbible.com/) standard. However, here I am implementing the normal OAuth 1.0 standard.  

```
# Semantics3 Keys 
sem3Key <- "SEMXXXXXXXXXXXXXXX"
sem3Secret <- "NTXXXXXXXXXXX"
srch <- "Samsung Galaxy"



# Create the oauth token 
oAuthEndpoint <- oauth_endpoint( "requestToken", "authorize", "access_token",base_url="https://api.semantics3.com/v1/")
sem3App <- oauth_app("sem3",key = sem3Key, secret = sem3Secret)
sem3Token <- oauth1.0_token(oAuthEndpoint, sem3App, cache = FALSE)

url <- paste0('https://api.semantics3.com/test/v1/products?q={"search": "',srch,'"}')

#Creates the request 
req <- GET(url, config(token = sem3Token))
stop_for_status(req)
content(req)

```
and I get the following error returned: 

> Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401).

I'm not sure where to start here and wondering if someone might know how to accomplish this though I'd really like to have this implemented in R.

**Comment by hadley** [comment] 2017-07-24 13:26
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2017-08-01 13:33
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-08-01 13:33 UTC
Labels: feature, oauth, reprex
