### ISSUE TITLE
Looks like passing query string with headers fails

### ISSUE THREAD

**Issue by ajijohn** [r-lib/httr#426] opened 2017-02-06 23:24 UTC
//Sample here 
```
auth_hdr = paste('Bearer ',token,sep = "")
                           # set the REST endpoint
                           apis_ep = paste(url_mc,'microclim/status',sep = "")
                           rqst_json = GET(apis_ep,add_headers(Authorization = auth_hdr),query = list("requestId" = requestId))
```

When query string is not passed, request is sent through. If both headers and query string are passed, below error appears

Unsupported protocol
1: ma$status(request_id) at /Users/ajijohn/git/microclimRapi/tests/testthat/test-APIdirectory.R:19
2: GET(apis_ep, add_headers(Authorization = auth_hdr), query = list(requestId = requestId)) at /Users/ajijohn/git/microclimRapi/R/MicroclimAPI.R:47
3: request_perform(req, hu$handle$handle)
4: request_fetch(req$output, req$url, handle)
5: request_fetch.write_memory(req$output, req$url, handle)
6: curl::curl_fetch_memory(url, handle = handle)

**Comment by ajijohn** [comment] 2017-02-07 19:33
Tracked the issue. So If query string is passed, the url must have protocol i.e. http(s).  If only header is set, the url protocol rule is not enforced.

  url_mc = 'localhost:3000/'
   apis_ep = paste(url_mc,'microclim/requests',sep = "")
                           rqsts_json = GET(apis_ep, add_headers(Authorization = auth_hdr))
                       
  Works ok

 But, if header and query string is passed, url must have protocol as part of it i.e. url_mc = 'http://localhost:3000/'

 auth_hdr = paste('Bearer ',token,sep = "")
                           # set the REST endpoint
                           apis_ep = paste(url_mc,'microclim/status',sep = "")
                           rqst_json = GET(apis_ep,add_headers(Authorization = auth_hdr),query = list("requestId" = requestId))

Not sure, if its an issue, authors can comment and close.

**Comment by hadley** [comment] 2017-07-24 13:15
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2017-08-01 13:32
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-08-01 13:32 UTC
Labels: reprex
