### ISSUE TITLE
no https callback address

### ISSUE THREAD

**Issue by porfila** [r-lib/httr#526] opened 2018-05-24 07:30 UTC
It is not possible to set an https callback address. This is a problem as many platforms require  a https redirection address. In this case it is not possible to autenticate through httr / oauth2.

**Comment by hadley** [comment] 2018-11-21 18:06
Can you please provide more details?

**Comment by hadley** [comment] 2018-11-21 18:15
Oh this is a duplicate of #510

**Closed by hadley** 2018-11-21 18:15 UTC
Labels: feature, oauth :ping_pong:
