### ISSUE TITLE
URLs without protocol causes error in windows but not linux

### ISSUE THREAD

**Issue by florian-j-auer** [r-lib/httr#619] opened 2019-10-14 15:55 UTC
I got a different behavior using httr in windows and in linux. It apeared first time at the end of August on the automatic build of my bioconductor package (ndexr).

It seems that omitting the protocol in the url causes an error on windows machines since:
```r
httr::GET(url="www.ndexbio.org/v2/admin/status")
#Error in if (is_http) { : argument is of length zero
```
linux or mac os are not affected.

**Comment by cderv** [comment] 2019-10-14 19:33
I think this is an issue with `curl` with `curl::fetch_memory` resulting differently on windows and linux. 

This is with curl 4.2.

On rstudio cloud, with R 3.6.0
``` r
library(curl)
    url <- "www.ndexbio.org/v2/admin/status"
    h <- new_handle()
    resp <- curl_fetch_memory(url, handle = h)
    resp$url
#> [1] "http://www.ndexbio.org/v2/admin/status"
```

<sup>Created on 2019-10-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

With Windows 10, on my computer, 
``` r
library(curl)
url <- "www.ndexbio.org/v2/admin/status"
h <- new_handle()
resp <- curl_fetch_memory(url, handle = h)
resp$url
#> [1] "www.ndexbio.org/v2/admin/status"
```

<sup>Created on 2019-10-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

As you see, the http is added in the result on linux, but not on windows. 
`httr` is currently testing the curl result to determine if the result is http or not, and that is where the error is. There must have been a change in curl I guess...

**Comment by cderv** [comment] 2019-10-14 19:47
I did further test on windows and I found that it worked with curl 3.3 but not with curl 4.0. 
In 4.0, there was an upgrade to libcurl 7.64.1. So the issue is in curl.

**Comment by cderv** [comment] 2019-10-14 19:59
I have just also realise that this is a duplicates of https://github.com/r-lib/httr/issues/607

**Comment by jonathon-love** [comment] 2019-10-15 00:55
hi,

i must be missing something, because i can't see how this error could be caused by curl. `parse_url()` will return a `scheme` of `NULL` when the scheme is missing:

https://github.com/r-lib/httr/blob/master/R/url.r#L38-L48

then `request_perform()` fails here because `$scheme` is NULL with that error:

https://github.com/r-lib/httr/blob/master/R/request.R#L159-L161

trivial fix is for `parse_url()` to set the scheme to `http` when none is provided.

happy to submit a PR.

cheers

**Comment by cderv** [comment] 2019-10-15 05:44
You spotted the right lines, but `parse_url` then `is_http` are on `resp$scheme` with `resp` being the response from `request_fetch` which uses `curl_fetch_memory`
https://github.com/r-lib/httr/blob/6b84c576f866956e01835e1b6f02c55c8012d4e0/R/request.R#L148
hence the hint on curl behavior. 
There was a change of behavior in curl 4.0 on windows. Before, the scheme was added by curl itself, after it wasn't. On linux it is still the case, the scheme is added. having a different behavior on windows and linux is not ideal.

However, I completely agree that a fix could be done in httr directly by handling missing scheme before doing `request_fetch`.  Though it should not break the initial fix while assuming a missing scheme is for http because the he aim of `is_http` is to deal with non http method (introduced in #549),

**Comment by cderv** [comment] 2019-10-15 18:05
> It possible that the curl behavior is now intented

From a comment from curl developer in https://github.com/jeroen/curl/issues/209#issuecomment-542127937, it seems it could be a regression

**Comment by cderv** [comment] 2019-10-16 15:08
This is now fixed in last dev version of curl 
``` r
# install last dev version
# remotes::install_github("jeroen/curl")
library(curl)
packageVersion("curl")
#> [1] '4.2.9000'
url <- "www.ndexbio.org/v2/admin/status"
h <- new_handle()
resp <- curl_fetch_memory(url, handle = h)
resp$url
#> [1] "http://www.ndexbio.org/v2/admin/status"

library(httr)
#> 
#> Attaching package: 'httr'
#> The following object is masked from 'package:curl':
#> 
#>     handle_reset
packageVersion("httr")
#> [1] '1.4.1'
res <- GET(url="www.ndexbio.org/v2/admin/status")
status_code(res)
#> [1] 200
```

<sup>Created on 2019-10-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jonathon-love** [comment] 2019-10-16 21:55
it would still be good to merge #620 though ... the lag between fixes and them arriving in debian/ubuntu distros is often very long. the ubuntu LTS, for example, will probably never receive that update.

**Closed** 2020-04-03 15:51 UTC
