### ISSUE TITLE
printing method of response object <unknown>

### ISSUE THREAD

**Issue by danilito19** [r-lib/httr#382] opened 2016-07-11 20:22 UTC
Creating an httr response object like

`out <-   httr:::response(
      status_code = 200L,
      content = charToRaw(jsonlite::toJSON(list(data = "it works!"), auto_unbox = TRUE)),
      headers = list(`Content-Type`= "application/json")
    )`

and calling out in an R session, prints

`Response []
  Date: NULL
  Status: 200
  Content-Type: <unknown>
  Size: 20 B
<BINARY BODY>`

Shouldn't Content-Type be  "application/json"?

**Comment by hadley** [comment] 2017-07-24 08:06
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by hadley** [comment] 2017-08-01 13:32
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-08-01 13:32 UTC
Labels: reprex
