### ISSUE TITLE
oauth2.0_token: Authentication complete. Error: is.list(x) is not TRUE

### ISSUE THREAD

**Issue by syphon5** [r-lib/httr#425] opened 2017-01-22 16:41 UTC
I'm trying to connect to the Twitch API via HTTR oauth2 and I am running into an error after authentication.

`twitch <- oauth_endpoint(
  authorize = "https://api.twitch.tv/kraken/oauth2/authorize",
  access =    "https://api.twitch.tv/kraken/oauth2/token"
)

app <- oauth_app("twitch", "CLIENTID", "SECRET")

token <- oauth2.0_token(twitch, app, scope = "user_read", user_params = c(redirect_uri="http://localhost:1410/"),
                        use_basic_auth = TRUE, cache=TRUE
)`

Firing token opens a browser window that says authentication is successful. R reports the following:
> Waiting for authentication in browser...
> Press Esc/Ctrl + C to abort
> Authentication complete.
> Error: is.list(x) is not TRUE

Below is the traceback()
`9: stop(sprintf(ngettext(length(r), "%s is not TRUE", "%s are not all TRUE"), 
       ch), call. = FALSE, domain = NA)
8: stopifnot(is.list(x), is.list(val))
7: utils::modifyList(user_params, req_params)
6: init_oauth2.0(self$endpoint, self$app, scope = self$params$scope, 
       user_params = self$params$user_params, type = self$params$type, 
       use_oob = self$params$use_oob, use_basic_auth = self$params$use_basic_auth)
5: self$init_credentials()
4: .subset2(public_bind_env, "initialize")(...)
3: Token2.0$new(app = app, endpoint = endpoint, params = params, 
       cache_path = cache)
2: oauth2.0_token(twitch, app, scope = "user_read", user_params = c(redirect_uri = "http://localhost:1410/"), 
       use_basic_auth = TRUE, cache = TRUE)
1: as.list(oauth2.0_token(twitch, app, scope = "user_read", user_params = c(redirect_uri = "http://localhost:1410/"), 
       use_basic_auth = TRUE, cache = TRUE))`

Thoughts?

**Comment by hadley** [comment] 2017-07-24 13:14
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2017-08-01 13:32
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-08-01 13:32 UTC
Labels: oauth, reprex
