### ISSUE TITLE
Always get 401 when attempting to use reddit API

### ISSUE THREAD

**Issue by karigunnarsson** [r-lib/httr#482] opened 2017-09-12 23:42 UTC
My apologies if i'm just missing something obvious, but having exhausted google, and trying to go through everything step by step, i can't help but feel this may be appropriate to post as an issue.

I'm more or less using an unedited version of the demo, only replacing the public, secret key and appname, but i always get 401. It opens up reddit and retrieves the code just fine, but fails on retrieving the token itself with a 401.

```r
library(httr)

# 1. Find OAuth settings for reddit:
#    https://github.com/reddit/reddit/wiki/OAuth2
reddit <- oauth_endpoint(
  authorize = "https://www.reddit.com/api/v1/authorize",
  access =    "https://www.reddit.com/api/v1/access_token"
)

# 2. Register an application at https://www.reddit.com/prefs/apps
app <- oauth_app(appname = "Comment extractor",
                 key = "rrG5wfgHkm5Kvw",
                 secret = "<my secret key>")

# 3b. If get 429 too many requests, the default user_agent is overloaded.
# If you have an application on Reddit then you can pass that using:
token <- oauth2.0_token(
  reddit, app,
  scope = c("read", "modposts"),
  use_basic_auth = TRUE,
  config_init = user_agent("some_agent")
)
```
Resulting in this error
```
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in oauth2.0_access_token(endpoint, app, code = code, user_params = user_params,  : 
  Unauthorized (HTTP 401). Failed to get an access token.
```
The keys should be fine, i've triple checked them and used them with PRAM (the python reddit API wrapper) without issue, though PRAM requires your username/password so they're not authenticating in the same way it seems.

I'm using the httr version 1.3.1 , with R version 3.4.1

**Comment by Dextr0city** [comment] 2017-09-23 21:08
I would also like to add the following: The demo is from the 28th of July, when we were at version 1.2.1 (release date:4th of July 2017), now we are at 1.3.1 (release date: 21st of  August 107) and the oauth_2.0_access_token function and the user agent where added in version 1.3.0 (release date: 16th of August 2017) .
Here is a link to what changed since 1.3 (after the demo): https://github.com/r-lib/httr/releases

I have tried to run the demo on 1.2.1, but I bumped on the "Too Many Requests (RFC 6585) (HTTP 429)." error, because I could not specify the user_agent in that version.

**Comment by GregoireCoppens** [comment] 2017-11-06 15:41
I have found a solution to our problem!
Pull request #485 has solved our problem by making init.oauth2.0() passes use_basic_auth.
So you can install his httr version by adding following lines:
```
#install.packages("devtools")  
library(devtools)  
devtools::install_github("r-lib/httr#485")
library(httr)  
```

Here is my full code that worked for me (don't foret to define key and secret):
```
#install.packages("httr")
#install.packages("devtools")
library(devtools)
devtools::install_github("r-lib/httr#485")
library(httr)

# 1. Find OAuth settings for reddit:
#    https://github.com/reddit/reddit/wiki/OAuth2
endpoint <- oauth_endpoint(
  authorize = "https://www.reddit.com/api/v1/authorize",
  access =    "https://www.reddit.com/api/v1/access_token"
)

# 2. Register an application at https://www.reddit.com/prefs/apps
app <- oauth_app("Test_App", key, secret)

# 3b. If get 429 too many requests, the default user_agent is overloaded.
# If you have an application on Reddit then you can pass that using:
token <- oauth2.0_token(
  endpoint = endpoint, 
  app=app,
  scope = c("read", "modposts"),
  use_basic_auth = TRUE,
#  cache = F,
  config_init = user_agent("Testing Oauth with httr")
)

#trying to make a call
#Important! Make sure to put oauth.reddit.com instad of reddit.com!
request_url <- "https://oauth.reddit.com/r/AskReddit/comments/7az0np/what_is_the_most_pointless_piece_of_information/.json"
response <- GET(request_url,
                user_agent("Testing Oauth with httr"),
                config(token = token)
                )

content(response, "text")
```

**Comment by dracovich** [comment] 2018-02-05 21:26
Sorry for the really late reply here, but yeah this fixes it for me too, hopefully they'll merge the fix soon.

**Comment by hadley** [comment] 2018-11-22 00:04
Duplicate of #484

**Closed by hadley** 2018-11-22 00:04 UTC
