### ISSUE TITLE
Error if request url without scheme

### ISSUE THREAD

**Issue by mannau** [r-lib/httr#607] opened 2019-08-20 08:10 UTC
If a request is done for a URL without a scheme, e.g. 

```httr::POST("hostname.com", H, body = body, encode = "json", ...)```
instead of
```httr::POST("https://hostname.com", H, body = body, encode = "json", ...)```

the resulting response url also contains only `hostname.com` in the `$url` field. This leads to a problem in `httr:::request_perform` since the resulting [`url_scheme` is NULL](https://github.com/r-lib/httr/blob/d7195c2afda788e80f64cab2d0277b14949a9490/R/request.R#L159), subsequently 
```tolower(url_scheme) %in% c("http", "https")``` is `logical(0)` and `if (is_http) {` leads to

```
Error in if (is_http) { : argument is of length zero
```

This feels like a bug to me (or at least should be handled), however, I have no idea for a nice workaround (yet).

**Comment by jonathon-love** [comment] 2019-09-01 04:37
so using GET(), etc. *without* a scheme used to work with earlier versions of `httr`, but no longer does.

i feel like the simplest mod here (and i'm happy to open a PR) is to modify `parse_url()` such that it returns a default of `http` if no scheme is provided (which is the same behaviour that web-browsers use, i.e. if you omit the scheme, it's treated as `http`)

thoughts?

**Comment by cderv** [comment] 2019-10-14 20:01
Duplicate of #619

**Closed** 2020-04-03 15:49 UTC
