### ISSUE TITLE
Must specify atleast one of URL or handle

### ISSUE THREAD

**Issue by KaranKhullar** [r-lib/httr#511] opened 2018-03-23 19:54 UTC
I have been trying to access this page : "https://employers.indeed.com/api/v1/campaigns?perPage=30" using Indeed API. 
I am not able to generate  oauth2.0_token. Not sure what I am doing wrong ?
Error I get after authentication complete in browser : 
**Error in handle_url(handle, url, ...) : 
Must specify at least one of url or handle**

Indeed Documentation Link : [http://opensource.indeedeng.io/api-documentation/docs/oauth/#before-you-start](url)

Can someone please help ?

```
`library(httr)
library(httpuv)
library(Rcpp)

in_endpoint <- oauth_endpoint(request = NULL,
                              authorize = "https://secure.indeed.com/account/oauth?client_id=YOUR CLIENT ID &redirect_uri=http://www.viewyourindeedcampaigns.com/oauth/indeed&response_type=code",
                              access = NULL,
                              base_url = "https://employers.indeed.com/api/v1/campaigns?perPage=30")
in_app <- oauth_app("your app name",
                    key = "client id",
                    secret = "client secret",
                    redirect_uri = "http://127.0.0.1:1410")
in_token <- oauth2.0_token(endpoint = in_endpoint,
                           app = in_app,
                           type = "code",
                          cache = T,
                           as_header  = TRUE,
                           scope = "https://employers.indeed.com/api/v1/campaigns?perPage=30" )
```

`

**Comment by hadley** [comment] 2018-11-21 18:23
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by hadley** [comment] 2018-12-04 14:34
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2018-12-04 14:34 UTC
Labels: reprex
