### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle) :    SSL connect error

### ISSUE THREAD

**Issue by KBPsystem777** [r-lib/httr#419] opened 2017-01-04 16:08 UTC
Good day!

I am following this line:

# 3. Get OAuth credentials
twitter_token <- oauth1.0_token(oauth_endpoints("twitter"), myapp)

and then it gave me an error like this: 
***_*Error in curl::curl_fetch_memory(url, handle = handle) :    SSL connect error**_**

How can I pass  this error? Thanks

**Comment by stephlocke** [comment] 2017-04-18 11:53
I'm now getting this on travis-ci with https calls in an APII package where it previously passed. Updating to latest libcurl4-openssl-dev didn't help. Don't want to hack using peer verification disabling (see #262 )

**Comment by hadley** [comment] 2017-07-24 09:26
@jeroen any ideas?

**Comment by hadley** [comment] 2017-07-24 09:26
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2017-08-01 13:33
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-08-01 13:33 UTC
Labels: reprex
