### ISSUE TITLE
Still problems with authentication / caching of credentials

### ISSUE THREAD

**Issue by dfv-ms** [r-lib/httr#481] opened 2017-09-11 11:10 UTC
I'm using RGoogleAnalytics which uses httr for authentication. With httr version 1.2.1 everything works fine: The first time I run it on a server I get asked for an authorization code and an url is shown. I call the url in my desktop-browser and fill in the response -> Access granted.
The second time the cached data in .httr-oauth is used.

But with httr version 1.3.1 I don't get an url to call:

```
httpuv not installed, defaulting to out-of-band authentication
Enter authorization code:
```
It seems also to ignore the caching-file. The one generated with 1.2.1 doesn't work.

Any idea how to fix it? I don't really want to stay at httr 1.2.1 forever :-(

**Comment by jennybc** [comment] 2017-09-11 12:51
This sounds a lot like a small problem with httr 1.3.0 that got fixed with 1.3.1. It's worth double-checking that you really are using 1.3.1 on all the relevant machines.

**Comment by dfv-MartinStingl** [comment] 2017-09-11 12:57
I really do use 1.3.1 as I'm forcing to install both versions in my tests.

```
library(devtools)
install_version("httr", version = "1.3.1", repos = "http://cran.r-project.org")
library("RGoogleAnalytics")
client.id <- "<client.id>"
client.secret <- "<client.secret>"

token <- Auth(client.id,client.secret)
```

```
sessionInfo()
```
returns 1.3.1, too

**Comment by jennybc** [comment] 2017-09-11 13:13
You're the second person to report trouble with RGoogleAnalytics very recently. Maybe there's some specific glitch re: RGoogleAnalytics + httr 1.3.1.

**Comment by JerryWho** [comment] 2017-09-16 11:39
In some cases I've got the problem that httr wants to start the browser but there isn't one on my server. So I patched httr that I always get the url to point the browser manually to even if httr thinks it started the browser. 
(I'm not sure if this patch should be part of the main packet. I works for me... https://github.com/JerryWho/httr/commit/4067bd8d55a574346b6720c58fc7fd8e78f5de2e)

Or I copy .httr-oauth from my desktop to the server. But watch out: The file should be created by httr 1.3.1. An older versions seems to create another problem...

**Comment by jennybc** [comment] 2017-09-16 14:37
@JerryWho It sounds like you should set `httr_oob_default` to `TRUE` in an `.Renviron` file on the server. Instead of that patch. Or do I miss something?

**Comment by dfv-MartinStingl** [comment] 2017-09-18 11:15
Setting httr_oob_default didn't help. I'm still being asked for the code without an url. I used the patch above.

**Comment by vjcitn** [comment] 2018-04-10 18:02
I am finding that httr 1.2.1 with options(httr_oob_default=TRUE) will, when used in the absence of a browser, generate a URL that can be used to authenticate and generate a token for use in the browserless session.  This process does not occur with httr 1.3.1, one simply get a "Enter authorization code:" prompt.  I can provide more details if there is interest; this has to do with bigrquery usage.

**Comment by vjcitn** [comment] 2018-04-24 14:25
In a system without a browser, httr 1.3.1 will not reveal to the user the text of url_handle (e.g., https://accounts.google.com/o/oauth2/auth?client_id=4657...) that is revealed in httr 1.2.1 when httr_oob_default = TRUE. @JerryWho's patch seems potentially useful.  I have still not figured out why BROWSE behaves differently between the two versions on browserless systems.

**Comment by hadley** [comment] 2018-11-22 00:05
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by vjcitn** [comment] 2018-11-22 02:40
i no longer have access to a relevant system.  you can close the issue; if i get relevant info i will file.

**Comment by hadley** [comment] 2018-11-22 14:30
I may also be that #518 will turn out to be the longer term fix for this problem. It seems like a flow more suited to non-interactive scenarios.

**Closed by hadley** 2018-11-22 14:30 UTC
Labels: reprex
