### ISSUE TITLE
POST ignoring encode="form"?

### ISSUE THREAD

**Issue by jgrn307** [r-lib/httr#421] opened 2017-01-10 01:27 UTC
I think I found the previous issue I had (nothing to do with equal sign).  Consider the following two scenarios:

###

curl  -d 'jsonRequest={"username":"testuser","password":"testpassword"}' "http://httpbin.org/post" -vvv

Results in:
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {
    "jsonRequest": "{\"username\":\"testuser\",\"password\":\"testpassword\"}"
  }, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "61", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.51.0"
  }, 
  "json": null, 
  "origin": "71.9.19.10", 
  "url": "http://httpbin.org/post"
}

### 

Now, trying to replicate this with httr:
content(POST(url="http://httpbin.org/post",body='jsonRequest={"username":"testuser","password":"testpassword"}',encode="form",verbose(data_in = T, info = T, ssl = T)))

Results in:
<<  {
<<    "args": {}, 
<<    "data": "jsonRequest={\"username\":\"testuser\",\"password\":\"testpassword\"}", 
<<    "files": {}, 
<<    "form": {}, 
<<    "headers": {
<<      "Accept": "application/json, text/xml, application/xml, */*", 
<<      "Accept-Encoding": "gzip, deflate", 
<<      "Content-Length": "61", 
<<      "Host": "httpbin.org", 
<<      "User-Agent": "libcurl/7.51.0 r-curl/2.3 httr/1.2.1"
<<    }, 
<<    "json": null, 
<<    "origin": "71.9.19.10", 
<<    "url": "http://httpbin.org/post"
<<  }

Notice the portion I WANT to be sent to the form is being sent as "data".  How do I go about fixing this?

**Comment by hadley** [comment] 2017-07-24 09:27
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by hadley** [comment] 2017-08-01 13:33
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-08-01 13:33 UTC
Labels: reprex
