### ISSUE TITLE
I am getting the error message “Insecure Login Blocked: You can’t get an access token or log in to this app from an insecure page. Try re-loading the page as https://”

### ISSUE THREAD

**Issue by Sb9309** [r-lib/httr#515] opened 2018-03-28 00:14 UTC
I have add Facebook login product and changed setting as per the attachment, Still not able to connect to Facebook page.
![capture](https://user-images.githubusercontent.com/37716029/38001564-5eb015cc-3225-11e8-82c1-fe8694cc5a0c.PNG)

Command using in Rstudio:
appID <- "My app ID" 
appSecret <- "My app secret
fb_oauth <- fbOAuth(app_id=appID, app_secret=appSecret, extended_permissions = TRUE)

**Comment by Hugosimon29** [comment] 2018-04-04 18:59
I have the same problem, please help...

**Comment by Sb9309** [comment] 2018-04-04 19:02
Hi,

Please try below link, it might help:
Insecure Login Blocked: You can't get an access token or log in to this app
from an insecure page. Try re-loading the page as https://
<https://stackoverflow.com/questions/49403748/insecure-login-blocked-you-cant-get-an-access-token-or-log-in-to-this-app-from>

Thanks,
Sukriti

*Best Regards,*

Sukriti Bhadoria

**Comment by cderv** [comment] 2018-04-04 20:34
I think this is a duplicate #510 but issue is still there too.

**Comment by Hugosimon29** [comment] 2018-04-04 20:41
Perhaps using some tools provided by a library such as hello.js you could login from localhost. I already solved but migrating to https but I leave this link to see if it serves: https://adodson.com/hello.js/#features

**Comment by kamalhappysanz** [comment] 2018-04-05 11:29
![fb secure login](https://user-images.githubusercontent.com/26597676/38363540-a91bc042-38f2-11e8-97a8-2a3803a5594d.JPG)


Can some one help me in this

**Comment by Promos10** [comment] 2018-04-10 07:01
I also get same error. My site have SSL enabled still shows error. Can anyone help?

**Comment by jacielluve** [comment] 2018-04-11 18:11
Hello, i have my site in http, and image from @kamalhappysanz  is apearing when i click fb login button.

do i need https in order to use FB login buttons??

**Comment by Hugosimon29** [comment] 2018-04-11 18:15
Yes, the Facebook policies require the use of https

**Comment by Carlitosuk** [comment] 2018-04-13 14:03
Hi all,

im having the same issue any chance tow to fix this issue (Insecure Login Blocked: You can't get an access token or log in to this app from an insecure page. Try re-loading the page as https://)

**Comment by Hugosimon29** [comment] 2018-04-13 19:12
The policies of the Facebook API restrict access to http pages, only access to https pages is allowed. There are libraries that you can use that allow you to visit your page from http for example https://www.npmjs.com/package/fbgraph

**Comment by Carlitosuk** [comment] 2018-04-14 05:12
Hiya,
Thanks for getting back to me I already have https on my website and Facebook login but unfortunately still giving me the same error which I have mentioned on he previous message any help please?
Thanks

**Comment by lokprakashpandey** [comment] 2018-04-14 16:13
Same problem.......It says "Insecure Login Blocked: You can't get an access token or log in to this app from an insecure page. Try re-loading the page as https://"........Anybody found solution

**Comment by JMVasquezR** [comment] 2018-04-18 15:06
they solved it, I have the same problem

**Comment by lokprakashpandey** [comment] 2018-04-18 16:45
Thanks I have solved mine already by installing a certificate and providing a https redirect URI

**Comment by JMVasquezR** [comment] 2018-04-18 16:49
You could help me with the type of configuration you have. because I also have the certifcate but the same error keeps coming up

**Comment by kamalhappysanz** [comment] 2018-04-19 03:33
@Carlitosuk you have to try another method it wont worked for me

**Comment by JMVasquezR** [comment] 2018-04-20 23:26
solve it, thanks

**Comment by EzraPro** [comment] 2018-05-01 08:38
I just resolved this issue on a website i manage with this steps:
sign-in to your facebook developers platform -- under facebook login -- go to Settings -- Valid OAuth Redirect URIs -- (after filling your app domain details, Copy and Paste the code below Ctrl&Shift V) "replace the example.com with the domain name you're activating social login for"
https://example.com/?SuperSocializerAuth=Facebook

It should work fine!, just say thanks to my mail: ezracreativeproductions@gmail.com
But if you would like me to help you fix it simple contact me on: admin@ezracreativeproductions.com or call: +2348186479089.

**Comment by demoblockchainapi** [comment] 2018-05-03 08:39
Duplicate of #515

**Comment by veerapandian22** [comment] 2018-05-09 10:49
Anybody found solution for this?
You can’t get an access token or log in to this app from an insecure page. Try re-loading the page as https://

**Comment by sunil-tamang** [comment] 2018-05-09 13:57
anyone here to help us.......?

**Comment by selvaonline** [comment] 2018-05-12 03:45
Add the below line in the package.json file

  "scripts": {
    "start": "set HTTPS=true&&react-scripts start",

**Comment by kvt227** [comment] 2018-05-16 17:37
I had the same problem and currently I fixed it with this article:
[Visual Studio 2017 - Resolving SSL/TLS connections problems with IIS Express](https://www.pluralsight.com/guides/visual-studio-2017-resolving-ssl-tls-connections-problems-with-iis-express)
--> **I changed my localhost from "http" to "https"** in MVC5.
I found this video for PHP, too: [Facebook Application Development Tutorial With Graph Api and php sdk In Urdu/Hindi 2018](https://www.youtube.com/watch?v=A4RYXvInhBc).
Hope that can help someone.

**Comment by sebastianlivin** [comment] 2018-05-17 11:45
I also have the same problem.
If anyone can give direction to solve will be helpful.

**Comment by kamalhappysanz** [comment] 2018-05-17 11:52
For all  the above i have   Use the Https for login and its working fine...

**Comment by cderv** [comment] 2018-05-18 05:47
FWIW, a discussion has been opened in [community.rstudio.com](https://community.rstudio.com/t/fboauth-integration-with-r-and-facebook/8536). It could be more efficient to continues discussions there.

**Comment by StepanyanAlbert** [comment] 2018-06-17 05:27
Having same problem  but redirect url is set to https://example.com so not sure why still throws insecure error

**Comment by EzraPro** [comment] 2018-06-18 13:08
redirect url should be set to https://enter your domain  name here.com
  not example

**Comment by hadley** [comment] 2018-11-21 18:15
Duplicate of #510

**Closed by hadley** 2018-11-21 18:15 UTC

**Comment by tauhidul0821** [comment] 2019-02-26 17:16
create a file on root directory name .env
write HTTPS=true
and save 
done

**Comment by tauhidul0821** [comment] 2019-02-26 17:17
> ![fb secure login](https://user-images.githubusercontent.com/26597676/38363540-a91bc042-38f2-11e8-97a8-2a3803a5594d.JPG)
> 
> Can some one help me in this

create a file on root directory name .env
write HTTPS=true
and save
done

**Comment by skm19860915** [comment] 2019-05-03 09:54
I saw the same error. please help. what is solution?

**Comment by cderv** [comment] 2019-05-03 11:39
See the last answer in the linked issue 
https://github.com/r-lib/httr/issues/510#issuecomment-441280660

There is a demo for oauth2 with facebook

**Comment by zinmyoswe** [comment] 2019-05-20 21:57
Assuming On windows
`XAMPP server

similar for other environment - download and extract for cacert.pem here (a clean file format/data)`
[https://curl.haxx.se/docs/caextract.html](url)

-put it here
C:\xampp\php\extras\ssl\cacert.pem

-in your php.ini put this line in this section ("c:\xampp\php\php.ini"):

```php
;;;;;;;;;;;;;;;;;;;;
; php.ini Options  ;
;;;;;;;;;;;;;;;;;;;;

curl.cainfo = "C:\xampp\php\extras\ssl\cacert.pem"
```

restart your webserver/apache

**Comment by Carlitosuk** [comment] 2019-10-07 07:09
Hi,

Thanks for the quick replied I have updated my website already last week to https but unfortunately Facebook keep giving me this error 
Any suggestions please?

Regards

**Comment by Labohkip81** [comment] 2019-10-21 09:23
I don't seem to find a workaround for this error.

**Comment by gondaljutt** [comment] 2020-07-13 10:51
The only thing which worked for me was that the Login App in Facebook was in **_development_** mode, I changed the mode to **_Live_** & it seems to be working fine.

**Comment by krabeeputh** [comment] 2020-09-27 15:53
I got the same problem. [Django SSL server](https://github.com/teddziuba/django-sslserver) helps to solve this problem for Facebook OAuth.

**Comment by yaakoubox** [comment] 2021-02-12 07:31
you have to get SSL certificate there is free in aws or buy one from your domain and then add it to your app then you get https url

**Comment by arikarim** [comment] 2021-04-04 10:05
For all who get the same error:
Create  .env file inside the root of your project and put  HTTPS=true
if you use http//localhost for your Facebook website URL change it to https//localhost and wait a bit.

chears:)))

**Comment by sanchit203** [comment] 2021-06-26 12:33
For all those who are still facing this problem. I have found a solution using all the resources provided in above comments. First you have to create a SSL certificate for your localhost and mkcert will do that easily for you. You can find how to use mkcert [https://web.dev/how-to-use-local-https/](url) here, after creating files you can see how to add these in [https://www.section.io/engineering-education/how-to-get-ssl-https-for-localhost/](url) here.
